package app.tshepo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BankConnectionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBankConnectionAllPropertiesEquals(BankConnection expected, BankConnection actual) {
        assertBankConnectionAutoGeneratedPropertiesEquals(expected, actual);
        assertBankConnectionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBankConnectionAllUpdatablePropertiesEquals(BankConnection expected, BankConnection actual) {
        assertBankConnectionUpdatableFieldsEquals(expected, actual);
        assertBankConnectionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBankConnectionAutoGeneratedPropertiesEquals(BankConnection expected, BankConnection actual) {
        assertThat(actual)
            .as("Verify BankConnection auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBankConnectionUpdatableFieldsEquals(BankConnection expected, BankConnection actual) {
        assertThat(actual)
            .as("Verify BankConnection relevant properties")
            .satisfies(a -> assertThat(a.getHolderLogin()).as("check holderLogin").isEqualTo(expected.getHolderLogin()))
            .satisfies(a -> assertThat(a.getConnectedAt()).as("check connectedAt").isEqualTo(expected.getConnectedAt()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getMaskedAccount()).as("check maskedAccount").isEqualTo(expected.getMaskedAccount()))
            .satisfies(a -> assertThat(a.getAccountType()).as("check accountType").isEqualTo(expected.getAccountType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBankConnectionUpdatableRelationshipsEquals(BankConnection expected, BankConnection actual) {
        // empty method
    }
}
