package app.tshepo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CredentialAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCredentialAllPropertiesEquals(Credential expected, Credential actual) {
        assertCredentialAutoGeneratedPropertiesEquals(expected, actual);
        assertCredentialAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCredentialAllUpdatablePropertiesEquals(Credential expected, Credential actual) {
        assertCredentialUpdatableFieldsEquals(expected, actual);
        assertCredentialUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCredentialAutoGeneratedPropertiesEquals(Credential expected, Credential actual) {
        assertThat(actual)
            .as("Verify Credential auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCredentialUpdatableFieldsEquals(Credential expected, Credential actual) {
        assertThat(actual)
            .as("Verify Credential relevant properties")
            .satisfies(a -> assertThat(a.getHolderLogin()).as("check holderLogin").isEqualTo(expected.getHolderLogin()))
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getPurpose()).as("check purpose").isEqualTo(expected.getPurpose()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getIssuedAt()).as("check issuedAt").isEqualTo(expected.getIssuedAt()))
            .satisfies(a -> assertThat(a.getExpiresAt()).as("check expiresAt").isEqualTo(expected.getExpiresAt()))
            .satisfies(a -> assertThat(a.getIssuerDid()).as("check issuerDid").isEqualTo(expected.getIssuerDid()))
            .satisfies(a -> assertThat(a.getSdJwt()).as("check sdJwt").isEqualTo(expected.getSdJwt()))
            .satisfies(a -> assertThat(a.getClaimsSummary()).as("check claimsSummary").isEqualTo(expected.getClaimsSummary()))
            .satisfies(a -> assertThat(a.getVcRef()).as("check vcRef").isEqualTo(expected.getVcRef()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCredentialUpdatableRelationshipsEquals(Credential expected, Credential actual) {
        // empty method
    }
}
