package app.tshepo.domain;

import static app.tshepo.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class IssuedClaimAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIssuedClaimAllPropertiesEquals(IssuedClaim expected, IssuedClaim actual) {
        assertIssuedClaimAutoGeneratedPropertiesEquals(expected, actual);
        assertIssuedClaimAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIssuedClaimAllUpdatablePropertiesEquals(IssuedClaim expected, IssuedClaim actual) {
        assertIssuedClaimUpdatableFieldsEquals(expected, actual);
        assertIssuedClaimUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIssuedClaimAutoGeneratedPropertiesEquals(IssuedClaim expected, IssuedClaim actual) {
        assertThat(actual)
            .as("Verify IssuedClaim auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIssuedClaimUpdatableFieldsEquals(IssuedClaim expected, IssuedClaim actual) {
        assertThat(actual)
            .as("Verify IssuedClaim relevant properties")
            .satisfies(a -> assertThat(a.getClaimType()).as("check claimType").isEqualTo(expected.getClaimType()))
            .satisfies(a -> assertThat(a.getOperator()).as("check operator").isEqualTo(expected.getOperator()))
            .satisfies(a ->
                assertThat(a.getThreshold()).as("check threshold").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getThreshold())
            )
            .satisfies(a -> assertThat(a.getCurrency()).as("check currency").isEqualTo(expected.getCurrency()))
            .satisfies(a -> assertThat(a.getPeriodMonths()).as("check periodMonths").isEqualTo(expected.getPeriodMonths()))
            .satisfies(a -> assertThat(a.getMet()).as("check met").isEqualTo(expected.getMet()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIssuedClaimUpdatableRelationshipsEquals(IssuedClaim expected, IssuedClaim actual) {
        assertThat(actual)
            .as("Verify IssuedClaim relationships")
            .satisfies(a -> assertThat(a.getCredential()).as("check credential").isEqualTo(expected.getCredential()));
    }
}
