package app.tshepo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class VerificationEventAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVerificationEventAllPropertiesEquals(VerificationEvent expected, VerificationEvent actual) {
        assertVerificationEventAutoGeneratedPropertiesEquals(expected, actual);
        assertVerificationEventAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVerificationEventAllUpdatablePropertiesEquals(VerificationEvent expected, VerificationEvent actual) {
        assertVerificationEventUpdatableFieldsEquals(expected, actual);
        assertVerificationEventUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVerificationEventAutoGeneratedPropertiesEquals(VerificationEvent expected, VerificationEvent actual) {
        assertThat(actual)
            .as("Verify VerificationEvent auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVerificationEventUpdatableFieldsEquals(VerificationEvent expected, VerificationEvent actual) {
        assertThat(actual)
            .as("Verify VerificationEvent relevant properties")
            .satisfies(a -> assertThat(a.getVerifiedAt()).as("check verifiedAt").isEqualTo(expected.getVerifiedAt()))
            .satisfies(a -> assertThat(a.getResult()).as("check result").isEqualTo(expected.getResult()))
            .satisfies(a -> assertThat(a.getDisclosedClaims()).as("check disclosedClaims").isEqualTo(expected.getDisclosedClaims()))
            .satisfies(a -> assertThat(a.getCredentialRef()).as("check credentialRef").isEqualTo(expected.getCredentialRef()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVerificationEventUpdatableRelationshipsEquals(VerificationEvent expected, VerificationEvent actual) {
        assertThat(actual)
            .as("Verify VerificationEvent relationships")
            .satisfies(a -> assertThat(a.getApiKey()).as("check apiKey").isEqualTo(expected.getApiKey()));
    }
}
