package app.tshepo.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class VerifierApiKeyAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVerifierApiKeyAllPropertiesEquals(VerifierApiKey expected, VerifierApiKey actual) {
        assertVerifierApiKeyAutoGeneratedPropertiesEquals(expected, actual);
        assertVerifierApiKeyAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVerifierApiKeyAllUpdatablePropertiesEquals(VerifierApiKey expected, VerifierApiKey actual) {
        assertVerifierApiKeyUpdatableFieldsEquals(expected, actual);
        assertVerifierApiKeyUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVerifierApiKeyAutoGeneratedPropertiesEquals(VerifierApiKey expected, VerifierApiKey actual) {
        assertThat(actual)
            .as("Verify VerifierApiKey auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVerifierApiKeyUpdatableFieldsEquals(VerifierApiKey expected, VerifierApiKey actual) {
        assertThat(actual)
            .as("Verify VerifierApiKey relevant properties")
            .satisfies(a -> assertThat(a.getOwnerLogin()).as("check ownerLogin").isEqualTo(expected.getOwnerLogin()))
            .satisfies(a -> assertThat(a.getLabel()).as("check label").isEqualTo(expected.getLabel()))
            .satisfies(a -> assertThat(a.getKeyHash()).as("check keyHash").isEqualTo(expected.getKeyHash()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()))
            .satisfies(a -> assertThat(a.getCallCount()).as("check callCount").isEqualTo(expected.getCallCount()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVerifierApiKeyUpdatableRelationshipsEquals(VerifierApiKey expected, VerifierApiKey actual) {
        // empty method
    }
}
